# push.rb config file

# API Data
push_api:
  url: "https://api.pushover.net/1/messages.json"
  home: "a6a165nqzhh5ti31pxyqyxkt61irm9"
  robotics: "akp6w35kcik5dhr5d6e58x93fk425s"
  user: "uihm386s9p3x5pnv3xy1ae1k93rmek"
  limit: 10000
  limit_url: "https://api.pushover.net/1/apps/limits.json"

# Push Configuration
push:
  title_home: "HomeServer Alert"
  title_work: "WorkMachine Alert"
  message: "Generic Message - Please configure (config.yaml)"
  priority:
    - -2            #0
    - -1            #1
    - 0             #2
    - 1             #3
    - 2             #4
  sound:
    - pushover      #0
    - bike          #1
    - bugle         #2
    - cashregister  #3
    - classical     #4
    - cosmic        #5
    - falling       #6
    - gamelan       #7
    - incoming      #8
    - intermission  #9
    - magic         #10
    - mechanical    #11
    - pianobar      #12
    - siren         #13
    - spacealarm    #14
    - tugboat       #15
    - alien         #16
    - climb         #17
    - persistent    #18
    - echo          #19
    - updown        #20
    - vibrate       #21
    - none          #22
  custom_sound: ""
  device1: "MyPhone"
  device2: "iphone"
  timestamp: ""
  html: 0
  ttl: ""
  url: ""
  url_title: ""
  res_file: "responses.txt"

# Attachments - configured for base64 encoding
#file_path will be used to encode the attachment
#image to base64 when the flag is set to 1
image:
  flag: 1
  type: "image/png"
  file_path: "./opt/0.png"
  max_size: 2621440

# Emergency Priority Config (in seconds)
emergency:
  flag: 0
  retry: 60
  expire: 3600
  callback_url: ""
  receipt_file: "emg_receipts.txt"
